name: Pascal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Installing FPC
      run: |
        sudo apt update
        sudo apt install -y fpc
      
    - name: Building pascal programs
      run: |
        mkdir -p build/cache
        shopt -s globstar
        for file in ./**/*.pas; do fpc -Tlinux ${file} -obuild/cache/${file##*/} ; done && rm -rf build/cache/*
        
    - name: Building & run test pascal programs
      run: |
        mkdir -p build/cache
        shopt -s globstar
        for file in ./**/*Test.pas; do fpc -Tlinux ${file} -obuild/cache/${file##*/} && ./build/cache/${file##*/} ; done && rm -rf build/cache/*
