name: Pascal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Installing FPC
      run: |
        sudo apt update
        sudo apt install -y fpc
      
    - name: Building test pascal programs
      run: |
        mkdir -p build/cache
        shopt -s globstar
        for file in src/**/*Test.pas; do fpc -Tlinux ${file} -obuild/cache/${file##*/}.test ; done
        
    - name: Test run programs
      run: |
        echo -e "\n\n=============== Running test programs ===============\n\n"
        for file in build/cache/*; do ./build/cache/${file##*/}.test && echo -e "\n\n" ; done
        echo -e "\n\n=============== Running test programs ===============\n\n"
      
    - name: Building pascal programs
      run: |
        mkdir -p build/cache
        shopt -s globstar
        for file in src/**/*.pas; do fpc -Tlinux ${file} -obuild/cache/${file##*/} ; done
        
    - name: Cleaning all build ouputs
      run: rm -rf build/cache/*
        
